Fixed test setup issues

diff --git a/.github/workflows/publish-test-results.yml b/.github/workflows/publish-test-results.yml
--- a/.github/workflows/publish-test-results.yml
+++ b/.github/workflows/publish-test-results.yml
@@ -55,11 +55,26 @@ jobs:
           fi
         env:
           CI: true
-          
+
       - name: Fetch GitHub Repo Data
         run: |
-          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/ApGroups/notes-app-react)
+          if [ -z "${GITHUB_REPOSITORY}" ]; then
+            echo "Error: GITHUB_REPOSITORY is undefined"
+            exit 1
+          fi
+
+          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}"
+          echo "Fetching data from $URL..."
+
+          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$URL")
+
+          if [ -z "$response" ]; then
+            echo "Error: No response from GitHub API"
+            exit 1
+          fi
+
           echo "Repo data: $response"
+
 
   publish-to-alva:
     uses: DevSkillsHQ/publish-test-results-workflow/.github/workflows/publish-test-results.yml@main
